---
sudo: required
dist: trusty
language: python
cache: pip
python:
- '2.7'

install:
  # Install AWS CLI
  - pip install awscli
  - aws --version
  # Install Terraform
  - TERRAFORM_VERSION="0.10.2"
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

before_script:
  # Determine environment
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
script:
  - |
    if [ -z "${ENV}" ]; then
      echo "${TRAVIS_BRANCH} is not a branch to deploy."
    else
      source ./scripts/switch-role.sh
      terraform init
      terraform get
      terraform workspace new ${ENV}
      terraform plan
    fi

deploy:
  - provider: script
    script: terraform plan
    skip_cleanup: true
    on:
      branch: deploy/*
