---
sudo: required
dist: trusty
language: python
cache: pip
python:
- '2.7'

install:
  # Install AWS CLI
  - pip install awscli
  - aws --version
  # Install Terraform
  - wget https://releases.hashicorp.com/terraform/0.7.13/terraform_0.7.13_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

before_script:
  # Determine environment
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
script:
  - |
    if [ -z "${ENV}" ]; then
      echo "${TRAVIS_BRANCH} is not a branch to deploy."
    else
      source ./scripts/switch-role.sh
      ./terraform-env.sh ${ENV} get
      ./terraform-env.sh ${ENV} plan
    fi

deploy:
  - provider: script
    script: ./terraform-env.sh ${ENV} apply
    skip_cleanup: true
    on:
      branch: deploy/*
